apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-sever
          image: diegots.azurecr.io/config-server:1.0.0
          ports:
            - name: http
              containerPort: 8080
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: config-server-svc
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: ms-customer