server:
  port: 8001
spring:
  config:
    name: config-server
  cloud:
    config:
      server:
        git:
          default-label: feature/config-data
          #default-label: developer
          uri: https://github.com/Diego9713/config-data
          username: Diego9713
          password: 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
  security:
    user:
      name: root
      password: s3cr3t
